"""
Auth plugin — JWT bearer token validation.
For demo purposes, a shared secret is used.
Tokens are pre-generated by the attack simulator for legitimate clients.
"""
import os
import time
from jose import jwt, JWTError
from fastapi import HTTPException, Request

SECRET_KEY = os.environ.get("JWT_SECRET", "api-security-demo-secret-key-2024")
ALGORITHM  = "HS256"

# Token issued at startup for valid clients
def create_token(client_id: str, expires_in: int = 3600) -> str:
    payload = {
        "sub": client_id,
        "iat": int(time.time()),
        "exp": int(time.time()) + expires_in,
    }
    return jwt.encode(payload, SECRET_KEY, algorithm=ALGORITHM)


def validate_token(request: Request) -> dict:
    """
    Validates JWT Bearer token from Authorization header.
    Returns decoded payload or raises HTTPException.
    """
    auth_header = request.headers.get("Authorization", "")
    if not auth_header.startswith("Bearer "):
        raise HTTPException(
            status_code=401,
            detail="Missing or invalid Authorization header",
            headers={"WWW-Authenticate": "Bearer"},
        )
    token = auth_header.removeprefix("Bearer ").strip()
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        return payload
    except JWTError as e:
        raise HTTPException(
            status_code=401,
            detail=f"Invalid token: {e}",
            headers={"WWW-Authenticate": "Bearer"},
        )
